services:
    jekyll:
        image: jekyll/jekyll
        ports:
            - 4001:4001
            - 35730:35730
        volumes:
            - .:/srv/jekyll:Z
            - ./vendor/bundle/:/usr/local/bundle:Z
        environment:
            - TZ=Asia/Taipei
        command: jekyll serve --force_polling --livereload --port 4001 --livereload-port 35730
