services:
    jekyll:
        image: bretfisher/jekyll-serve
        ports:
            - 11181:4000
            - 35730:35730
        volumes:
            - .:/site:Z
            - .:/srv/jekyll:Z
            - ./vendor/bundle/:/usr/local/bundle:Z
        environment:
            - TZ=Asia/Taipei
        command: jekyll serve --force_polling -H 0.0.0.0 --port 4000
